version: '2'
services:
  db:
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=bookshelf
      - POSTGRES_PASSWORD=bookshelf
      - POSTGRES_DB=biblio
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - '8082:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=nguyen_marc@live.fr
      - PGADMIN_DEFAULT_PASSWORD=opste963
    depends_on:
      - db

volumes:
  postgres_data:
